/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cubesforthepackage;

import javax.swing.JRadioButton;
import java.util.ArrayList;

/**
 *
 * @author Mark
 */
public class CubesForTheScoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form CubesForTheScoreFrame
     */
    
    int selectedOption = 0;
    
    CubesForTheScore scoreTheTurn;
    
    ArrayList<JRadioButton> scoreOptions = new ArrayList<JRadioButton>();
    
    public CubesForTheScoreFrame() {
        initComponents();
        scoreOptions.add(onesRadioButton);
        scoreOptions.add(twosRadioButton);
        scoreOptions.add(threesRadioButton);
        scoreOptions.add(foursRadioButton);
        scoreOptions.add(fivesRadioButton);
        scoreOptions.add(sixesRadioButton);
        scoreOptions.add(threeOfAKindRadioButton);
        scoreOptions.add(fourOfAKindRadioButton);
        scoreOptions.add(fullHouseRadioButton);
        scoreOptions.add(smallStraightRadioButton);
        scoreOptions.add(largeStraightRadioButton);
        scoreOptions.add(fiveOfAKindRadioButton);
        scoreOptions.add(chanceRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        onesRadioButton = new javax.swing.JRadioButton();
        largeStraightRadioButton = new javax.swing.JRadioButton();
        fiveOfAKindRadioButton = new javax.swing.JRadioButton();
        fourOfAKindRadioButton = new javax.swing.JRadioButton();
        twosRadioButton = new javax.swing.JRadioButton();
        threesRadioButton = new javax.swing.JRadioButton();
        fullHouseRadioButton = new javax.swing.JRadioButton();
        foursRadioButton = new javax.swing.JRadioButton();
        smallStraightRadioButton = new javax.swing.JRadioButton();
        sixesRadioButton = new javax.swing.JRadioButton();
        fivesRadioButton = new javax.swing.JRadioButton();
        threeOfAKindRadioButton = new javax.swing.JRadioButton();
        chanceRadioButton = new javax.swing.JRadioButton();

        jButton1.setText("Score");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Choose a score section Below");

        buttonGroup1.add(onesRadioButton);
        onesRadioButton.setText("Ones");

        buttonGroup1.add(largeStraightRadioButton);
        largeStraightRadioButton.setText("Large Straight");

        buttonGroup1.add(fiveOfAKindRadioButton);
        fiveOfAKindRadioButton.setText("Five of a Kind");

        buttonGroup1.add(fourOfAKindRadioButton);
        fourOfAKindRadioButton.setText("Four of a Kind");

        buttonGroup1.add(twosRadioButton);
        twosRadioButton.setText("Twos");

        buttonGroup1.add(threesRadioButton);
        threesRadioButton.setText("Threes");

        buttonGroup1.add(fullHouseRadioButton);
        fullHouseRadioButton.setText("Full House");

        buttonGroup1.add(foursRadioButton);
        foursRadioButton.setText("Fours");

        buttonGroup1.add(smallStraightRadioButton);
        smallStraightRadioButton.setText("Small Straight");

        buttonGroup1.add(sixesRadioButton);
        sixesRadioButton.setText("Sixes");

        buttonGroup1.add(fivesRadioButton);
        fivesRadioButton.setText("Fives");

        buttonGroup1.add(threeOfAKindRadioButton);
        threeOfAKindRadioButton.setText("Three of a Kind");

        buttonGroup1.add(chanceRadioButton);
        chanceRadioButton.setText("Chance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(onesRadioButton)
                            .addComponent(twosRadioButton)
                            .addComponent(threesRadioButton)
                            .addComponent(foursRadioButton)
                            .addComponent(fivesRadioButton)
                            .addComponent(sixesRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(smallStraightRadioButton)
                                    .addComponent(fullHouseRadioButton)
                                    .addComponent(fourOfAKindRadioButton)
                                    .addComponent(threeOfAKindRadioButton)
                                    .addComponent(largeStraightRadioButton))
                                .addComponent(fiveOfAKindRadioButton))
                            .addComponent(chanceRadioButton))))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onesRadioButton)
                    .addComponent(threeOfAKindRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twosRadioButton)
                    .addComponent(fourOfAKindRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threesRadioButton)
                    .addComponent(fullHouseRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foursRadioButton)
                    .addComponent(smallStraightRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fivesRadioButton)
                    .addComponent(largeStraightRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixesRadioButton)
                    .addComponent(fiveOfAKindRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chanceRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for(int i = 0; i < 13; i++)
        {
            if(scoreOptions.get(i).isSelected())
            {
                scoreOptions.get(i).setEnabled(false);
                selectedOption = i + 1;
                break;
            }
        }
        scoreTheTurn.score(selectedOption);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CubesForTheScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CubesForTheScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CubesForTheScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CubesForTheScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CubesForTheScoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chanceRadioButton;
    private javax.swing.JRadioButton fiveOfAKindRadioButton;
    private javax.swing.JRadioButton fivesRadioButton;
    private javax.swing.JRadioButton fourOfAKindRadioButton;
    private javax.swing.JRadioButton foursRadioButton;
    private javax.swing.JRadioButton fullHouseRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton largeStraightRadioButton;
    private javax.swing.JRadioButton onesRadioButton;
    private javax.swing.JRadioButton sixesRadioButton;
    private javax.swing.JRadioButton smallStraightRadioButton;
    private javax.swing.JRadioButton threeOfAKindRadioButton;
    private javax.swing.JRadioButton threesRadioButton;
    private javax.swing.JRadioButton twosRadioButton;
    // End of variables declaration//GEN-END:variables
}
